import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextUILayout from "./NextUIProvider";
import NavbarComponent from "@/components/layouts/navbar/NavbarComponent";
import { Suspense } from "react";
import LoadingComponent from "./loading";
import Error from "./error";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
// import { ErrorBoundary } from "next/dist/client/components/error-boundary";



// import { metadata } from './layout';


// not yet complete such as font and metadta 

export const metadata:Metadata = {
  title:{
    template: "%s -MyShop",
    default:"MyShop"
  },
   description: "this is description shop "
  
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  icons: {
    icon: "/assets/pic.jpg",
  },
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}    >
        <NextUILayout>
          <NavbarComponent />
            
            {/* waiting data */}
           <Suspense fallback={<LoadingComponent/>} >

            <ErrorBoundary errorComponent={Error}>
            {children}
            </ErrorBoundary>
            
          </Suspense>
        </NextUILayout>
      </body>
    </html>
  );
}
